name: Docker - Server

on: [push]

jobs:
  test-and-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.18.3"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Convert repo name to lowercase
        id: case-change
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username zihadmahiuddin --password-stdin
      - name: Docker build
        run: docker build -t docker.pkg.github.com/${{ steps.case-change.outputs.lowercase }}/server:latest .
      - name: Docker push tag latest
        run: docker push docker.pkg.github.com/${{ steps.case-change.outputs.lowercase }}/server:latest
        if: github.ref == 'refs/heads/master'
